declare module '@kangc/v-md-editor'
declare module '@kangc/v-md-editor/lib/theme/vuepress.js'
declare module 'prismjs'
declare module '@kangc/v-md-editor/lib/plugins/mermaid/cdn'
declare module '@kangc/v-md-editor/lib/plugins/todo-list/index'
declare module '@kangc/v-md-editor/lib/plugins/line-number/index'
declare module '@kangc/v-md-editor/lib/plugins/highlight-lines/index'
declare module '@kangc/v-md-editor/lib/plugins/copy-code/index'