spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 90000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # There is no use for Redis for now
  # redis:
  #   host: localhost
  #   port: 6379
  #   password: password
  #   database: 0
  session:
    store-type: NONE
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  thymeleaf:
    cache: true
    mode: HTML
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.liux.blog: info
