spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 90000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  session:
    store-type: NONE
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  thymeleaf:
    cache: true
    mode: HTML
  jackson:
    time-zone: UTC

server:
  max-http-header-size: 1MB

mybatis:
  type-handlers-package: com.liux.blog.dao.typehandler
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.liux.blog: info

springfox:
  documentation:
    enabled: false
