server:
  max-http-request-header-size: 1MB
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
  tomcat:
    max-swallow-size: -1
    access-log:
      enabled: false
      pattern: "%{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}t %{X-Real-IP}i %r %s %b %{ms}T %{Referer}i %{User-Agent}i"
      directory: /dev
      prefix: stdout
      suffix: null
      buffered: false
      rotate: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 90000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  thymeleaf:
    cache: true
    mode: HTML
  jackson:
    time-zone: UTC
  main:
    allow-circular-references: true

mybatis:
  type-handlers-package: com.liux.blog.dao.typehandler
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    com.liux.blog: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false
